### ISSUE TITLE
Social distancing implementation on detector's result

### ISSUE THREAD

**Issue by JsonSadler** [JsonSadler/neuralet#2]
[had to delete previous repo as it was not a fork of neuralet]

Has to implement in libs/Core.py

@alpha-carinae29 Would you please make your PR again on this repo? Thanks again for your quick help and for your replies to my previous issues, sorry that I had to delete the previous one.

**Comment by alpha-carinae29** [comment]
No problem, I made a PR

**Comment by JsonSadler** [comment]
@alpha-carinae29 please review my last commit [
9127b9f ](https://github.com/JsonSadler/neuralet/commit/9127b9f8aa5c2e15b8973eeb9ec336daaebfeb61) and make sure it is doing what you intended to do. 
I just added a key named "centroid" for you.

**Comment by SoheilKoohi** [comment]
@JsonSadler it is great, but you should also make changes in `centroind_object_tracker.py` and replace every `bbox` key to `centroid`

**Comment by alpha-carinae29** [comment]
@JsonSadler it is great, but you also need to replace all of the `bbox` keys to `centroid` in `centroid__object_tracker.py`
